openapi: '3.0.3'
info:
  title: Post Management
  version: '1.0'
servers:
  - url: https://api.server/posts

components:
  schemas:
    createPost:
      type: object
      properties:
        userId:
          type: integer
        text:
          type: string
        
paths:
  /:
    post:
      requestBody: 
        content:
          application/json:
            schema:
              $ref : '#/components/schemas/createPost'
          
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: string
                  message:
                    type: string
                  data:
                    type: object
              example:
                    success: true
                    message: Post created
                    data: null
        '400':
          description: Invalid Input
        '500':
          description: Internal server Error
